# Generated by Django 2.2.15 on 2023-11-02 12:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0045_parkingarea_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='origin ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3879, verbose_name='geometry')),
                ('capacity_estimate', models.PositiveSmallIntegerField(
                    blank=True, null=True, verbose_name='capacity estimate')),
                ('event_start', models.DateTimeField(db_index=True, verbose_name='event start time')),
                ('event_end', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='event end time')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                             related_name='event_areas', to='parkings.EnforcementDomain')),
                ('parking_areas', models.ManyToManyField(blank=True, related_name='overlapping_event_areas',
                                                         to='parkings.ParkingArea', verbose_name='overlapping parking areas')),
            ],
            options={
                'verbose_name': 'event area',
                'verbose_name_plural': 'event areas',
            },
        ),
    ]
