# Generated by Django 2.2.15 on 2023-11-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0047_add_eventparking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingcheck',
            name='found_event_parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='parkings.EventParking', verbose_name='found event parking'),
        ),
    ]
