# Generated by Django 2.2.15 on 2023-11-10 11:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0048_parkingcheck_found_event_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedparking',
            name='location_gk25fin',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, db_index=True, null=True, srid=3879, verbose_name='location_gk25fin'),
        ),
        migrations.AddField(
            model_name='eventparking',
            name='location_gk25fin',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, db_index=True, null=True, srid=3879, verbose_name='location_gk25fin'),
        ),
        migrations.AddField(
            model_name='parking',
            name='location_gk25fin',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, db_index=True, null=True, srid=3879, verbose_name='location_gk25fin'),
        ),
    ]
