# Generated by Django 2.2.15 on 2023-11-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0049_add_field_location_gk25fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventarea',
            old_name='event_end',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='eventarea',
            old_name='event_start',
            new_name='time_start',
        ),
    ]
