# Generated by Django 2.2.15 on 2023-11-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0051_eventarea_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventarea',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('H', 'Hour'), ('D', 'Day')], max_length=1, null=True),
        ),
    ]
