# Generated by Django 2.2.15 on 2023-11-14 12:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0052_eventarea_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventarea',
            name='bus_stop_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, help_text='Comma separated list of bus stop numbers. e.g.: 123,345,678', null=True, size=None, verbose_name='bus stop numbers'),
        ),
    ]
