# Generated by Django 2.2.15 on 2023-11-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0053_eventarea_bus_stop_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventarea',
            name='time_end',
            field=models.DateTimeField(db_index=True, verbose_name='event end time'),
        ),
    ]
