# Generated by Django 2.2.15 on 2023-11-21 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0055_eventarea_add_time_period_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparking',
            name='event_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event_parkings', to='parkings.EventArea', verbose_name='event area'),
        ),
    ]
