# Generated by Django 2.2.15 on 2023-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0056_eventparking_event_area_not_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventarea',
            name='price_unit',
        ),
        migrations.AddField(
            model_name='eventarea',
            name='price_unit_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price unit length in hours'),
        ),
    ]
