# Generated by Django 2.2.15 on 2023-11-27 11:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0057_eventarea_remove_price_unit_add_price_unit_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAreaStatistics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_parking_count', models.PositiveIntegerField(default=0, verbose_name='total parking count')),
                ('total_parking_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total parking income')),
                ('total_parking_charges', models.PositiveIntegerField(default=0, verbose_name='total number of charges')),
                ('event_area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='parkings.EventArea', verbose_name='event area statistics')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
