# Generated by Django 2.2.15 on 2023-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0058_eventareastatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventarea',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
