# Generated by Django 4.2.8 on 2024-05-17 11:19

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0063_remove_permitarea_permitted_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedparking',
            name='domain',
            field=models.ForeignKey(db_index=False, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='parkings.enforcementdomain'),
        ),
        migrations.AlterField(
            model_name='archivedparking',
            name='operator',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT,
                                    to='parkings.operator', verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='archivedparking',
            name='parking_area',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='parkings.parkingarea', verbose_name='parking area'),
        ),
        migrations.AlterField(
            model_name='archivedparking',
            name='region',
            field=models.ForeignKey(blank=True, db_index=False, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='parkings.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='archivedparking',
            name='terminal',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='parkings.parkingterminal', verbose_name='terminal'),
        ),
        migrations.AlterField(
            model_name='archivedparking',
            name='zone',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='parkings.paymentzone', verbose_name='PaymentZone'),
        ),
        migrations.AlterField(
            model_name='eventparking',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='parkings.enforcementdomain'),
        ),
        migrations.AlterField(
            model_name='eventparking',
            name='event_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='parkings.eventarea', verbose_name='event area'),
        ),
        migrations.AlterField(
            model_name='eventparking',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='parkings.operator', verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='parkings.enforcementdomain'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='parkings.operator', verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='parking_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='parkings.parkingarea', verbose_name='parking area'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='parkings.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='parkings.parkingterminal', verbose_name='terminal'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='parkings.paymentzone', verbose_name='PaymentZone'),
        ),
        migrations.AlterField(
            model_name='parkingcheck',
            name='result',
            field=models.JSONField(
                blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='properties',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder,
                                   null=True, verbose_name='properties'),
        ),
    ]
