# Generated by Django 4.2.8 on 2024-06-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0064_alter_archivedparking_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventarea',
            name='is_test',
            field=models.BooleanField(
                default=False, help_text='if set to True the event area is ment only for testing purposes, can be deleted and is not serialized.', verbose_name='is test'),
        ),
    ]
