# Generated by Django 4.2.8 on 2025-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0065_eventarea_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventarea',
            name='is_test',
            field=models.BooleanField(default=False, help_text='if set to True the event area is ment only for testing purposes, can be deleted and is not visible in the public API.', verbose_name='is test'),
        ),
    ]
